types:
  feat: "âœ¨ "     # New feature
  fix: "ğŸ› "      # Bug fixes
  docs: "ğŸ“š "     # Documentation changes
  style: "ğŸ’ "    # Code style changes
  refactor: "â™»ï¸ " # Code refactoring
  perf: "âš¡ï¸ "    # Performance improvements
  test: "ğŸ§ª "     # Tests
  build: "ğŸ›  "    # Build system changes
  ci: "ğŸ‘· "       # CI/CD changes
  chore: "ğŸ§¹ "    # Other changes
  revert: "âª "   # Reverts
